### ISSUE TITLE
Update header logo & text

### ISSUE THREAD

**Issue by jessbeutler** [osmus/tasking-manager#123]
1. Update logo in header to OSM US logo
2. Alter header text: "Tasking Manager" > "OpenStreetMap US Tasking Manager"

Ideally how this would look: 
![image](https://user-images.githubusercontent.com/36767434/175999927-6d1eb38b-036f-4298-a02c-760303cbdd33.png)

**Comment by quincylvania** [comment]
Done as part of #247.
<img width="221" alt="Screenshot 2023-01-25 at 3 32 36 PM" src="https://user-images.githubusercontent.com/2046746/214683593-0c07b91d-c84e-4938-a20f-a154fe34ac43.png">
