### ISSUE TITLE
Update TM Branding

### ISSUE THREAD

**Issue by jessbeutler** [osmus/tasking-manager#247]
![TM Update](https://user-images.githubusercontent.com/36767434/212754647-517ba104-c49c-4451-9412-da952d9833fd.png)

Update TM Branding per mock-up above. Text included below: 

- [x] Mapping the United States together
- [x] Map for Public Good
Join the OpenStreetMap US community in improving open geospatial data that can be used to improve lives and decision-making in the United States and around the world.

- [x] Thousand of volunteers across the country are working together to close local data gaps and address civic, environmental, and social issues by crowdsourcing geospatial data.

- [x] Organizations, government agencies, and community volunteers use Tasking Manager to create projects for areas around the United States, and the world, where data is needed.
- [x] Trusted organizations and agencies across the United States use OpenStreetMap data to support their missions.
- [x] "The OpenStreetMap (OSM) project is a critical piece of open data infrastructure. For almost 20 years, OSM and the community that fuels it have created the world's de facto map. Because it is community-driven, more areas of the world are being mapped. Individual mappers can put themselves on the map and have a say in how their community appears on the map." - Kiri Carini, Development Seed

Notes:
- Replacement images TBD
- USGS & USDOT logos available in Public Domain Map repo

Branding colors:
`#59A336`
`#76C551`

**Comment by quincylvania** [comment]
This is pretty well done. It'll be live once #219 is merged and released.
