### ISSUE TITLE
Hide incompatible PDM editors in all cases

### ISSUE THREAD

**Issue by quincylvania** [osmus/tasking-manager#256]
There are a few screens where users could select map editors other than the PDMap editor for PDMap projects. Need to track these down and limit them.

**Comment by watmildon** [comment]
I see this on my task pages? Is it related? Should it be hidden?

![image](https://user-images.githubusercontent.com/118567155/220474390-3a1646b2-b5b0-4eb1-ad70-154c77637a47.png)

**Comment by quincylvania** [comment]
@watmildon Hmm yes this is related bug. Looks like it won't actually open the PD editor thankfully, but it's still wrong.
