### ISSUE TITLE
[BUG] Tab icon still has HOT logo

### ISSUE THREAD

**Issue by watmildon** [osmus/tasking-manager#257]
**Describe the bug**
The new look and feel rules but we still have the HOT logo in the title tab. It would reduce confusion even further if there was a different asset used.

**To Reproduce**
Open an OSMUS task manager tab.

**Expected behavior**
Some OSMUS brand logo? Maybe just a recolored HOT?

**Screenshots**
![image](https://user-images.githubusercontent.com/118567155/219822044-f0dd0b9a-ae9d-4e69-8335-09a91660e8c6.png)

**Desktop (please complete the following information):**

**Comment by quincylvania** [comment]
Thanks, this is #122 :)

**Comment by watmildon** [comment]
Me: quickly scans the 7 open issues... totally misses this. Siiiiigh. Sorry to cause extra noise.
