### ISSUE TITLE
Text for "contributions" tab does not match casing style for the rest of the page

### ISSUE THREAD

**Issue by watmildon** [osmus/tasking-manager#258]
**Describe the bug**
It's possible this is intentional but maybe also a simple fit and finish bug.

**To Reproduce**
Go to the Start Mapping page for a project.

**Expected behavior**
Text for this tab to have starting capital "Contributions"

**Screenshots**
![image](https://user-images.githubusercontent.com/118567155/219822199-f6e0780a-aba5-4509-a124-000b25ea5a5a.png)

**Comment by quincylvania** [comment]
Fixed in e93322c224d14723af9d8d1e2e2f84c7ae647f4d
