### ISSUE TITLE
[BUG] OSI approved logo missing from about page

### ISSUE THREAD

**Issue by wireguy** [osmus/tasking-manager#260]
**Describe the bug**

**To Reproduce**
1. Go to '[about page](https://tasks.openstreetmap.us/about)'
2. Look at:
![image](https://user-images.githubusercontent.com/47227325/219881763-6d6527bb-fef0-4606-89d3-7b29091ceb1e.png)

the url in the page source:
https://opensource.org/files/OSIApproved_1.png

tried going to that url directly, and received the message:
Multisite support not enabled

Logo guidelines at https://opensource.org/logo-usage-guidelines/
seem to point to this image
https://149753425.v2.pressablecdn.com/wp-content/uploads/2009/08/osi_standard_logo_0.png

**Comment by watmildon** [comment]
Was gonna ask about things like this. I filed this a few days ago against HOT here: https://github.com/hotosm/tasking-manager/issues/5594

In general should I file matching stuff here? Mention you? Happy with whatever you think is best.

**Comment by quincylvania** [comment]
@watmildon We'll be keeping up-to-date with HOT TM releases as much as possible, so you can open relevant issues over there. Feel free to mention me and I'll see if it's something we might fix for the OSMUS TM without waiting.
