### ISSUE TITLE
[BUG] inbox notifications url incorrect

### ISSUE THREAD

**Issue by wireguy** [osmus/tasking-manager#261]
click on notifications bell icon, takes you to https://tasks.openstreetmap.us/inbox

click on task
https://**tasking-manager-frontend.ondigitalocean.app**/projects/234/tasks/?search=36
but should be
https://tasks.openstreetmap.us/projects/234/tasks/?search=36

click on project
https://**tasking-manager-frontend.ondigitalocean.app**/projects/234
but should be
https://tasks.openstreemap.us/projects/234

**Comment by quincylvania** [comment]
@wireguy Thanks for reporting. I _think_ I was able to fix this on the server side for new notifications (existing notifications have hardcoded text and can't really be changed). But we'll keep an eye out for lingering issues.
