### ISSUE TITLE
[BUG] notification email not being sent?

### ISSUE THREAD

**Issue by wireguy** [osmus/tasking-manager#262]
Seems to be some items around email that are broken.
Not receiving email notifications on validated tasks.

**Comment by wireguy** [comment]
might be related?   in a comment box, if you try to add an email address by clicking the email dropdown, task dialog closes abruptly.

**Comment by quincylvania** [comment]
Oh yeah, I'm not surprised this stuff is broken 🤔

**Comment by iandees** [comment]
fwiw, I got task validation emails later last week after we set this up.

**Comment by quincylvania** [comment]
Moving to #274
